# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='algos.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x61lgos.proto*,\n\x0fObjectDetection\x12\n\n\x06YOLOV3\x10\x00\x12\r\n\tRETINANET\x10\x01*\xb2\x01\n\x0e\x43lassification\x12\t\n\x05VGG16\x10\x00\x12\t\n\x05VGG19\x10\x01\x12\x0c\n\x08RESNET50\x10\x02\x12\x0e\n\nRESNET50V2\x10\x03\x12\r\n\tRESNET101\x10\x04\x12\x0f\n\x0bRESNET101V2\x10\x05\x12\r\n\tRESNET152\x10\x06\x12\x0f\n\x0bRESNET152V2\x10\x07\x12\r\n\tMOBILENET\x10\x08\x12\x0f\n\x0bMOBILENETV2\x10\t\x12\x0c\n\x08XCEPTION\x10\n')
)

_OBJECTDETECTION = _descriptor.EnumDescriptor(
  name='ObjectDetection',
  full_name='ObjectDetection',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='YOLOV3', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETINANET', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=15,
  serialized_end=59,
)
_sym_db.RegisterEnumDescriptor(_OBJECTDETECTION)

ObjectDetection = enum_type_wrapper.EnumTypeWrapper(_OBJECTDETECTION)
_CLASSIFICATION = _descriptor.EnumDescriptor(
  name='Classification',
  full_name='Classification',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VGG16', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VGG19', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESNET50', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESNET50V2', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESNET101', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESNET101V2', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESNET152', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESNET152V2', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOBILENET', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOBILENETV2', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCEPTION', index=10, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=62,
  serialized_end=240,
)
_sym_db.RegisterEnumDescriptor(_CLASSIFICATION)

Classification = enum_type_wrapper.EnumTypeWrapper(_CLASSIFICATION)
YOLOV3 = 0
RETINANET = 1
VGG16 = 0
VGG19 = 1
RESNET50 = 2
RESNET50V2 = 3
RESNET101 = 4
RESNET101V2 = 5
RESNET152 = 6
RESNET152V2 = 7
MOBILENET = 8
MOBILENETV2 = 9
XCEPTION = 10


DESCRIPTOR.enum_types_by_name['ObjectDetection'] = _OBJECTDETECTION
DESCRIPTOR.enum_types_by_name['Classification'] = _CLASSIFICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
