# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipeline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dataset_pb2 as dataset__pb2
import algos_pb2 as algos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pipeline.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0epipeline.proto\x1a\rdataset.proto\x1a\x0b\x61lgos.proto\"\xa9\x02\n\x08Pipeline\x12\"\n\x08\x61\x64\x64_data\x18\x01 \x01(\x0e\x32\x07.Status:\x07PENDING\x12#\n\tlock_data\x18\x02 \x01(\x0e\x32\x07.Status:\x07PENDING\x12\"\n\x08set_algo\x18\x03 \x01(\x0e\x32\x07.Status:\x07PENDING\x12\x1f\n\x05train\x18\x04 \x01(\x0e\x32\x07.Status:\x07PENDING\x12\x33\n\x14\x64\x61taset_version_info\x18\x05 \x01(\x0b\x32\x15.dataset_version_meta\x12(\n\x11\x64\x61taset_meta_info\x18\x06 \x01(\x0b\x32\r.dataset_meta\x12*\n\x12tfrecord_meta_info\x18\x07 \x01(\x0b\x32\x0e.tfrecord_meta*\x04\x08\t\x10\x15\"\xbd\x01\n\x17ObjectDetectionPipeline2;\n\x0cinput_format\x12\t.Pipeline\x18\t \x01(\x0e\x32\x1a.ObjectDetectionDataFormat2.\n\talgorithm\x12\t.Pipeline\x18\n \x01(\x0e\x32\x10.ObjectDetection25\n\x11\x66\x65\x61ture_extractor\x12\t.Pipeline\x18\x0b \x01(\x0e\x32\x0f.Classification*1\n\x06Status\x12\x0b\n\x07PENDING\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\r\n\tCOMPLETED\x10\x02')
  ,
  dependencies=[dataset__pb2.DESCRIPTOR,algos__pb2.DESCRIPTOR,])

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PENDING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=538,
  serialized_end=587,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
PENDING = 0
RUNNING = 1
COMPLETED = 2



_PIPELINE = _descriptor.Descriptor(
  name='Pipeline',
  full_name='Pipeline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='add_data', full_name='Pipeline.add_data', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lock_data', full_name='Pipeline.lock_data', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='set_algo', full_name='Pipeline.set_algo', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='train', full_name='Pipeline.train', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataset_version_info', full_name='Pipeline.dataset_version_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataset_meta_info', full_name='Pipeline.dataset_meta_info', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tfrecord_meta_info', full_name='Pipeline.tfrecord_meta_info', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(9, 21), ],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=344,
)


_OBJECTDETECTIONPIPELINE = _descriptor.Descriptor(
  name='ObjectDetectionPipeline',
  full_name='ObjectDetectionPipeline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='input_format', full_name='ObjectDetectionPipeline.input_format', index=0,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='ObjectDetectionPipeline.algorithm', index=1,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_extractor', full_name='ObjectDetectionPipeline.feature_extractor', index=2,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=536,
)

_PIPELINE.fields_by_name['add_data'].enum_type = _STATUS
_PIPELINE.fields_by_name['lock_data'].enum_type = _STATUS
_PIPELINE.fields_by_name['set_algo'].enum_type = _STATUS
_PIPELINE.fields_by_name['train'].enum_type = _STATUS
_PIPELINE.fields_by_name['dataset_version_info'].message_type = dataset__pb2._DATASET_VERSION_META
_PIPELINE.fields_by_name['dataset_meta_info'].message_type = dataset__pb2._DATASET_META
_PIPELINE.fields_by_name['tfrecord_meta_info'].message_type = dataset__pb2._TFRECORD_META
DESCRIPTOR.message_types_by_name['Pipeline'] = _PIPELINE
DESCRIPTOR.message_types_by_name['ObjectDetectionPipeline'] = _OBJECTDETECTIONPIPELINE
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pipeline = _reflection.GeneratedProtocolMessageType('Pipeline', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINE,
  __module__ = 'pipeline_pb2'
  # @@protoc_insertion_point(class_scope:Pipeline)
  ))
_sym_db.RegisterMessage(Pipeline)

ObjectDetectionPipeline = _reflection.GeneratedProtocolMessageType('ObjectDetectionPipeline', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTDETECTIONPIPELINE,
  __module__ = 'pipeline_pb2'
  # @@protoc_insertion_point(class_scope:ObjectDetectionPipeline)
  ))
_sym_db.RegisterMessage(ObjectDetectionPipeline)

_OBJECTDETECTIONPIPELINE.extensions_by_name['input_format'].enum_type = dataset__pb2._OBJECTDETECTIONDATAFORMAT
Pipeline.RegisterExtension(_OBJECTDETECTIONPIPELINE.extensions_by_name['input_format'])
_OBJECTDETECTIONPIPELINE.extensions_by_name['algorithm'].enum_type = algos__pb2._OBJECTDETECTION
Pipeline.RegisterExtension(_OBJECTDETECTIONPIPELINE.extensions_by_name['algorithm'])
_OBJECTDETECTIONPIPELINE.extensions_by_name['feature_extractor'].enum_type = algos__pb2._CLASSIFICATION
Pipeline.RegisterExtension(_OBJECTDETECTIONPIPELINE.extensions_by_name['feature_extractor'])

# @@protoc_insertion_point(module_scope)
